overrides:
  constantinople@<3.1.1: '>=3.1.1'
  clean-css@<4.1.11: '>=4.1.11'
  uglify-js@<2.6.0: '>=2.6.0'
  uglify-js@<2.4.24: '>=2.4.24'
  express@<4.19.2: '>=4.19.2'
  body-parser@<1.20.3: '>=1.20.3'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
  express@<4.20.0: '>=4.20.0'
  path-to-regexp@<0.1.12: '>=0.1.12'
  path-to-regexp@<0.1.10: '>=0.1.10'
  cookie@<0.7.0: '>=0.7.0'
  qs@>=6.5.0 <6.5.3: '>=6.5.3'
